GET https://api.bilibili.com/x/space/wbi/acc/info?mid=163637592
Host: api.bilibili.com
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0


# > HTTP/1.1 200 OK
# > Date: Thu, 30 Mar 2023 11:16:43 GMT
# > Content-Type: application/json; charset=utf-8
# > Transfer-Encoding: chunked
# > Connection: keep-alive
# > Bili-Status-Code: 0
# > Bili-Trace-Id: 22101f7b05642480
# > X-Bili-Trace-Id: b6ada03449a73cb022101f7b05642480
# > X-Rid-Result: 2
# > Content-Encoding: gzip
# > Expires: Thu, 30 Mar 2023 11:16:42 GMT
# > Cache-Control: no-cache
# > X-Cache-Webcdn: BYPASS from blzone01
# >
# > {
# >   "code": 0,
# >   "message": "0",
# >   "ttl": 1,
# >   "data": {
# >     "mid": 163637592,
# >     "name": "老师好我叫何同学",
# >     "sex": "保密",
# >     "face": "https://i0.hdslb.com/bfs/face/492d0bb71749332040f9d812954fa0b52e66c490.jpg",
# >     "face_nft": 0,
# >     "face_nft_type": 0,
# >     "sign": "喜欢做贼有意思的视频 工作联系：xhaxx1123@163.com",
# >     "rank": 10000,
# >     "level": 6,
# >     "jointime": 0,
# >     "moral": 0,
# >     "silence": 0,
# >     "coins": 0,
# >     "fans_badge": true,
# >     "fans_medal": {
# >       "show": false,
# >       "wear": false,
# >       "medal": null
# >     },
# >     "official": {
# >       "role": 1,
# >       "title": "bilibili 2021百大UP主、2020年度最佳作品奖UP主",
# >       "desc": "",
# >       "type": 0
# >     },
# >     "vip": {
# >       "type": 2,
# >       "status": 1,
# >       "due_date": 1695571200000,
# >       "vip_pay_type": 0,
# >       "theme_type": 0,
# >       "label": {
# >         "path": "",
# >         "text": "年度大会员",
# >         "label_theme": "annual_vip",
# >         "text_color": "#FFFFFF",
# >         "bg_style": 1,
# >         "bg_color": "#FB7299",
# >         "border_color": "",
# >         "use_img_label": true,
# >         "img_label_uri_hans": "",
# >         "img_label_uri_hant": "",
# >         "img_label_uri_hans_static": "https://i0.hdslb.com/bfs/vip/8d4f8bfc713826a5412a0a27eaaac4d6b9ede1d9.png",
# >         "img_label_uri_hant_static": "https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/VEW8fCC0hg.png"
# >       },
# >       "avatar_subscript": 1,
# >       "nickname_color": "#FB7299",
# >       "role": 3,
# >       "avatar_subscript_url": "",
# >       "tv_vip_status": 0,
# >       "tv_vip_pay_type": 0
# >     },
# >     "pendant": {
# >       "pid": 0,
# >       "name": "",
# >       "image": "",
# >       "expire": 0,
# >       "image_enhance": "",
# >       "image_enhance_frame": ""
# >     },
# >     "nameplate": {
# >       "nid": 0,
# >       "name": "",
# >       "image": "",
# >       "image_small": "",
# >       "level": "",
# >       "condition": ""
# >     },
# >     "user_honour_info": {
# >       "mid": 0,
# >       "colour": null,
# >       "tags": []
# >     },
# >     "is_followed": false,
# >     "top_photo": "http://i1.hdslb.com/bfs/space/6c8654a697ae71bd18f27b8db775c45e2a02d5d6.png",
# >     "theme": {},
# >     "sys_notice": {},
# >     "live_room": {
# >       "roomStatus": 1,
# >       "liveStatus": 0,
# >       "url": "https://live.bilibili.com/5867219?broadcast_type=0&is_room_feed=0",
# >       "title": "何同学带你开箱 iPhone11 ",
# >       "cover": "http://i0.hdslb.com/bfs/vc/fe0c50ca27065a4261cf583a70f291697000bc98.jpg",
# >       "roomid": 5867219,
# >       "roundStatus": 0,
# >       "broadcast_type": 0,
# >       "watched_show": {
# >         "switch": true,
# >         "num": 20,
# >         "text_small": "20",
# >         "text_large": "20人看过",
# >         "icon": "https://i0.hdslb.com/bfs/live/a725a9e61242ef44d764ac911691a7ce07f36c1d.png",
# >         "icon_location": "",
# >         "icon_web": "https://i0.hdslb.com/bfs/live/8d9d0f33ef8bf6f308742752d13dd0df731df19c.png"
# >       }
# >     },
# >     "birthday": "",
# >     "school": null,
# >     "profession": {
# >       "name": "",
# >       "department": "",
# >       "title": "",
# >       "is_show": 0
# >     },
# >     "tags": null,
# >     "series": {
# >       "user_upgrade_status": 3,
# >       "show_upgrade_window": false
# >     },
# >     "is_senior_member": 0,
# >     "mcn_info": null,
# >     "gaia_res_type": 0,
# >     "gaia_data": null,
# >     "is_risk": false,
# >     "elec": {
# >       "show_info": {
# >         "show": true,
# >         "state": 1,
# >         "title": "",
# >         "icon": "",
# >         "jump_url": ""
# >       }
# >     },
# >     "contract": null
# >   }
# > }
